// Generated by CoffeeScript 1.6.3
var Storage,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Storage = (function() {
  function Storage() {}

  Storage.prototype.find = function(model, query, cb) {
    throw "not implemented";
  };

  Storage.prototype.get = function(model, query_or_id, cb) {
    throw "not implemented";
  };

  Storage.prototype.save = function(model, json) {
    throw "not implemented";
  };

  Storage.prototype.remove = function(model, query_or_id, cb) {
    throw "not implemented";
  };

  return Storage;

})();

Storage.Mongo = (function(_super) {
  __extends(Mongo, _super);

  function Mongo(conn_str) {
    this.mongojs = require('mongojs');
    this.db = this.mongojs(conn_str);
  }

  Mongo.prototype.demongofy = function(doc) {
    doc.id = doc._id.toString();
    delete doc._id;
    return doc;
  };

  Mongo.prototype.mongofy = function(json) {
    if (json.id) {
      json._id = this.mongojs.ObjectId(json.id);
      delete json.id;
    }
    return json;
  };

  Mongo.prototype.find = function(model, query, options, cb) {
    var _this = this;
    if (arguments.length === 3) {
      cb = options;
    } else if (arguments.length === 2) {
      cb = query;
    }
    return this.db.collection(model).find(this.mongofy(query), function(err, result) {
      return cb(err, result.map(_this.demongofy));
    });
  };

  Mongo.prototype.remove = function(model, query, cb) {
    var _this = this;
    return this.db.collection(model).remove(this.mongofy(query), function(err, num) {
      return cb(err, num);
    });
  };

  Mongo.prototype.save = function(model, json, cb) {
    var _this = this;
    return this.db.collection(model).save(this.mongofy(json), {
      safe: true
    }, function(err, doc) {
      return cb(err, doc && _this.demongofy(doc || null));
    });
  };

  return Mongo;

})(Storage);

module.exports = Storage;

/*
//@ sourceMappingURL=storage.map
*/
