// Generated by CoffeeScript 1.6.3
var Argon, exports;

Argon = {};

Argon.Observable = require('./observable');

Argon.Renderer = require('./renderer');

Argon.Route = require('./route');

Argon.View = require('./view');

Argon.Socket = require('./client/socket');

Argon.ClientModel = require('./client/model');

Argon.Model = Argon.ClientModel;

exports = module.exports = Argon;

if (typeof window !== "undefined" && window !== null) {
  window.Argon = exports;
}

/*
//@ sourceMappingURL=argon.map
*/
