// Generated by CoffeeScript 1.6.3
var Route, exports;

Route = (function() {
  function Route(pattern, view) {
    var re_str;
    this.pattern = pattern;
    this.view = view;
    re_str = this.pattern.replace(/\?/g, '([^/]+)').replace(/\*/g, '(.*)');
    this.re = new RegExp("^" + re_str + "$");
  }

  Route.prototype.reverse = function(params) {
    return this.pattern.replace(/[\?\*]/, function() {
      return params.shift();
    });
  };

  Route.prototype.match = function(url) {
    var params;
    if (params = url.match(this.re)) {
      return params.slice(1);
    }
  };

  return Route;

})();

exports = module.exports = Route;

/*
//@ sourceMappingURL=route.map
*/
