// Generated by CoffeeScript 1.6.3
var Storage, exports;

Storage = (function() {
  function Storage() {}

  Storage.prototype.find = function(model, query, cb) {
    throw "not implemented";
  };

  Storage.prototype.get = function(model, query_or_id, cb) {
    throw "not implemented";
  };

  Storage.prototype.save = function(model, json) {
    throw "not implemented";
  };

  Storage.prototype.remove = function(model, query_or_id, cb) {
    throw "not implemented";
  };

  return Storage;

})();

exports = module.exports = Storage;

/*
//@ sourceMappingURL=storage.map
*/
